USE test;
DROP TABLE IF EXISTS components;
create table components (id integer not null auto_increment, count integer, manufacturer varchar(255), name varchar(255), is_primary bit, primary key (id))
engine=MyISAM
DEFAULT CHARACTER SET = utf8;
INSERT INTO components (count, name, is_primary) VALUES (1,"Процессор",1);
INSERT INTO components (count, name, is_primary) VALUES (1,"Вентилятор",1);
INSERT INTO components (count, name, is_primary) VALUES (1,"Оперативная память",1);
INSERT INTO components (count, name, is_primary) VALUES (1,"SD карта",0);
INSERT INTO components (count, name, is_primary) VALUES (1,"Картридер",0);
INSERT INTO components (count, name, is_primary) VALUES (1,"Карта CompactFlash",0);
INSERT INTO components (count, name, is_primary) VALUES (1,"Флешка",0);
INSERT INTO components (count, name, is_primary) VALUES (1,"HDD",0);
INSERT INTO components (count, name, is_primary) VALUES (1,"SSD",1);
INSERT INTO components (count, name, is_primary) VALUES (1,"FDD",0);
INSERT INTO components (count, name, is_primary) VALUES (1,"CD-ROM",0);
INSERT INTO components (count, name, is_primary) VALUES (1,"DVD-ROM",0);
INSERT INTO components (count, name, is_primary) VALUES (1,"Внешний жесткий диск",0);
INSERT INTO components (count, name, is_primary) VALUES (1,"Звуковая карта",0);
INSERT INTO components (count, name, is_primary) VALUES (1,"Видеокарта",1);
INSERT INTO components (count, name, is_primary) VALUES (1,"TV тюнер",0);
INSERT INTO components (count, name, is_primary) VALUES (1,"Веб-камера",0);
INSERT INTO components (count, name, is_primary) VALUES (1,"Монитор",1);
INSERT INTO components (count, name, is_primary) VALUES (1,"Корпус",1);
INSERT INTO components (count, name, is_primary) VALUES (1,"Блоки питания",1);
INSERT INTO components (count, name, is_primary) VALUES (1,"Клавиатура",1);
INSERT INTO components (count, name, is_primary) VALUES (1,"Мышь",1);
INSERT INTO components (count, name, is_primary) VALUES (1,"Графический планшет",0);
INSERT INTO components (count, name, is_primary) VALUES (1,"Джойстик",0);
INSERT INTO components (count, name, is_primary) VALUES (1,"ADSL модем",0);
INSERT INTO components (count, name, is_primary) VALUES (1,"Wi-Fi адаптер,",0);
INSERT INTO components (count, name, is_primary) VALUES (1,"Источник бесперебойного питания",0);