USE test;
DROP TABLE IF EXISTS components;
create table components (id integer not null auto_increment, count integer, manufacturer varchar(255), name varchar(255), is_primary bit, primary key (id))
engine=MyISAM
DEFAULT CHARACTER SET = utf8;
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla01","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla02","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla03","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla04","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla05","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla06","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla07","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla08","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla09","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla10","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla11","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla12","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla13","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla14","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla15","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla16","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla17","aga",1);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla18","aga",1);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla19","aga",1);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla20","aga",1);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla21","aga",1);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla22","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla23","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla24","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla25","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla26","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla27","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla28","aga",1);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla29","aga",1);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla30","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla31","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla32","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla33","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla34","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla35","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla36","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla37","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla38","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla39","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla40","aga",0);
INSERT INTO components (count, manufacturer, name, is_primary) VALUES (1,"blabla41","aga",0);
